name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.7
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^23.2.7
  firebase_storage: ^11.5.5
  http: ^1.1.2


  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/pdf/
    - assets/images/

  uses-material-design: true
