// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// 
 //await Firebase.initializeApp(
 //  options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMDBb6BP7JbGybCRnhxdyNB6LN75Hd5o',
    appId: '1:243216632203:web:d0ccacac8b0ebb02c5c78e',
    messagingSenderId: '243216632203',
    projectId: 'gazooapp-f50d0',
    authDomain: 'gazooapp-f50d0.firebaseapp.com',
    storageBucket: 'gazooapp-f50d0.appspot.com',
    measurementId: 'G-S2JB4NWXPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuCqhYP-_wjxUbMBISCNqI_lqbeda1dg',
    appId: '1:243216632203:android:52f8f979438f25c4c5c78e',
    messagingSenderId: '243216632203',
    projectId: 'gazooapp-f50d0',
    storageBucket: 'gazooapp-f50d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7W3qhefbwgCNjGeIBhbocqK76SqaT5g',
    appId: '1:243216632203:ios:b25f4134c3acde8dc5c78e',
    messagingSenderId: '243216632203',
    projectId: 'gazooapp-f50d0',
    storageBucket: 'gazooapp-f50d0.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7W3qhefbwgCNjGeIBhbocqK76SqaT5g',
    appId: '1:243216632203:ios:a1e59a64f0ee212fc5c78e',
    messagingSenderId: '243216632203',
    projectId: 'gazooapp-f50d0',
    storageBucket: 'gazooapp-f50d0.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
